### ISSUE TITLE
Handling occasional timeouts or disruptions

### ISSUE THREAD

**Issue by noahd1** [collectiveidea/tinder#27]
After adding some logging lines to figure out what is going on, I realized that campfire's streaming API occasionally closes idle connections with a 400 error status code. When the disconnect happens, tinder picks up an error in its 'on_error' handler and [raises a "ListenFailed" error](https://github.com/collectiveidea/tinder/blob/master/lib/tinder/room.rb#L162).

This is somewhat reasonable behavior, though, [Campfire's Streaming API documentation](http://developer.37signals.com/campfire/streaming) notes that "API clients must be able to handle occasional timeouts or disruptions. Upon unexpected disconnection, API clients should wait for a few seconds before trying to reconnect." It doesn't seem that tinder follows this contract. 

Thoughts? Happy to submit a patch, but wanted to make sure my understanding is correct first.

**Comment by asheren** [comment]
Hi there! We're doing some open source maintenance work and closing old issues. If this issue is still applicable or you would still like it to be addressed, please re-open the issue by April 17, 2017. Thanks!
