### ISSUE TITLE
.find_room_by_name & .rooms result in NoMethodError

### ISSUE THREAD

**Issue by markbate** [collectiveidea/tinder#28]
Hi,
I got some errors while trying to get Campfire notifications going in CI Joe & decided to go digging.
I was initially getting the ActiveSupport 2.3 issue (https://github.com/collectiveidea/tinder/issues/24), but got around by installing 3.x
Things now seem to break when CI Joe calls Tinder::Campfire.find_room_by_name().

I went through with irb & seem to get an error whenever I call anything to do with room.

$ irb -rubygems

> require 'tinder'
> t = Tinder::Campfire.new('my_subdomain', :token => "my_token", :ssl => false)
> t.find_room_by_name("my_room")
> NoMethodError: undefined method `[]' for nil:NilClass
>     from /usr/lib/ruby/gems/1.8/gems/tinder-1.7.0/lib/tinder/campfire.rb:34:in`rooms'
>     from /usr/lib/ruby/gems/1.8/gems/tinder-1.7.0/lib/tinder/campfire.rb:46:in `find_room_by_name'
>     from (irb):4
> 
> t.rooms
> NoMethodError: undefined method `[]' for nil:NilClass
>     from /usr/lib/ruby/gems/1.8/gems/tinder-1.7.0/lib/tinder/campfire.rb:34:in`rooms'
>     from (rib):5

I have things running on Ubuntu 11.04 server, ruby 1.8.7, rubygems 1.3.7
tinder 1.7.0, activesupport 3.1.0, cijoe 0.9.2, faraday 0.7.4, faraday_middleware 0.7.0

any ideas?

**Comment by asheren** [comment]
Hi there! We're doing some open source maintenance work and closing old issues. If this issue is still applicable or you would still like it to be addressed, please re-open the issue by April 17, 2017. Thanks!
