### ISSUE TITLE
Let me test campfire responses

### ISSUE THREAD

**Issue by technoweenie** [collectiveidea/tinder#37]
So, I just broke campfire hooks on [GitHub services](https://github.com/github/github-services/blob/master/services/campfire.rb) for a few minutes.  I'm testing the unreleased Faraday 0.8 with some real code before I push it out.  I actually did add [one last minute tweak](https://github.com/technoweenie/faraday/commit/18dae1447d2e45b6ae023cdacbeca1741342fbb2) due to a Tinder test failure.  After that, everything passed (even on [her](https://github.com/remiprev/her)).  Perfect, ship it!

Boom!  It all blew up :(

Part of the reason is I'm actually testing the CF hook by [mocking the Tinder classes](https://github.com/github/github-services/blob/master/test/campfire_test.rb#L4) a bit.  So janky.

What do you guys think about something like this:

``` ruby
cf = Tinder::Campfire.stub(campfire_domain, :ssl => true, :token => data['token'])
cf.on_message do |some_shit|
  assert some_shit
end

room = cf.find_room_by_name(blah)
room.speak blah
```

It could use Faraday::Adapter::Test, and let applications test their integration without hitting Campfire.  I'm not super familiar with the codebase, but I'm totally down to make this happen.  Just let me know :+1: or :-1: :)

**Comment by asheren** [comment]
Hi there! We're doing some open source maintenance work and closing old issues. If this issue is still applicable or you would still like it to be addressed, please re-open the issue by April 17, 2017. Thanks!
