### ISSUE TITLE
Room#listen delay

### ISSUE THREAD

**Issue by ryanlecompte** [collectiveidea/tinder#40]
I'm experimenting with the Room#listen method for streaming. It seems like there's a significant delay between someone chatting in the channel actually receiving the message via Room#listen. Is this a known limitation? Is there any way to somehow shorten the delay?

Thanks!

**Comment by asheren** [comment]
Hi there! We're doing some open source maintenance work and closing old issues. If this issue is still applicable or you would still like it to be addressed, please re-open the issue by April 17, 2017. Thanks!
