### ISSUE TITLE
Rubyforge API docs and website are outdated.

### ISSUE THREAD

**Issue by masterkorp** [collectiveidea/tinder#43]
Its kinda of annoying, i just wasted an hour trying to login by [the old method](http://tinder.rubyforge.org/tinder/) 

Please mark them as deprecated at least.

Thanks.

**Comment by asheren** [comment]
Hi there! We're doing some open source maintenance work and closing old issues. If this issue is still applicable or you would still like it to be addressed, please re-open the issue by April 17, 2017. Thanks!
