### ISSUE TITLE
Cannot create room

### ISSUE THREAD

**Issue by trobrock** [collectiveidea/tinder#53]
``` ruby
campfire = Tinder::Campfire.new 'mysite', :token => '000000000000000'
campfire.create_room "testing"
=> nil
```

Not sure why the room wont create, this token is for an admin user. Is there any other config that is needed?

**Comment by asheren** [comment]
Hi there! We're doing some open source maintenance work and closing old issues. If this issue is still applicable or you would still like it to be addressed, please re-open the issue by April 17, 2017. Thanks!
