### ISSUE TITLE
Increase streaming timeout

### ISSUE THREAD

**Issue by josacar** [collectiveidea/tinder#62]
When joining and streaming a campfire room, a value of `6` seconds is passed into JSONStream, which is a too little value.

At this moment, 37Signals is sending a `1` value every 3 seconds to keep open the connection, so if one of these `keep-alive` packets is lost or delayed the client closes the connection and `Twitter::JSONStream` raises the following error:

```
/app/vendor/bundle/ruby/2.0.0/gems/twitter-stream-0.1.16/lib/twitter/json_stream.rb:131:in `<<': Could not parse data entirely (HTTP::Parser::Error)
   from /app/vendor/bundle/ruby/2.0.0/gems/twitter-stream-0.1.16/lib/twitter/json_stream.rb:131:in `receive_data'
   from /app/vendor/bundle/ruby/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
   from /app/vendor/bundle/ruby/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
   from /app/vendor/bundle/ruby/2.0.0/gems/thin-1.5.1/lib/thin/backends/base.rb:63:in `start'
   from /app/vendor/bundle/ruby/2.0.0/gems/thin-1.5.1/lib/thin/server.rb:159:in `start'
   from /app/vendor/bundle/ruby/2.0.0/gems/lita-2.3.0/lib/lita/robot.rb:98:in `block in run_app'
```

I've forked the repo and tried with a higher value ( 60 ) and no disconnection has happened yet.

**Comment by asheren** [comment]
Hi there! We're doing some open source maintenance work and closing old issues. If this issue is still applicable or you would still like it to be addressed, please re-open the issue by April 17, 2017. Thanks!
