### ISSUE TITLE
faraday_middleware dependency

### ISSUE THREAD

**Issue by rastkojokic** [collectiveidea/tinder#68]
Hi,

faraday_middleware gem dependency has 'locked' faraday gem version to <0.9. This way I am not able to upgrade faraday greater than 0.9...

Please let me know if I am missing something?

Best,
Rastko

**Comment by asheren** [comment]
Hi there! We're doing some open source maintenance work and closing old issues. If this issue is still applicable or you would still like it to be addressed, please re-open the issue by April 17, 2017. Thanks!
