### ISSUE TITLE
Room Creation Date

### ISSUE THREAD

**Issue by geoffreywiseman** [collectiveidea/tinder#73]
The campfire API includes the room's creation date, Tinder doesn't seem to expose this, near as I can tell. This has some value in terms of finding out how far back to dig for transcripts.

**Comment by asheren** [comment]
Hi there! We're doing some open source maintenance work and closing old issues. If this issue is still applicable or you would still like it to be addressed, please re-open the issue by April 17, 2017. Thanks!
