### ISSUE TITLE
request to follow SemVer/mention it in README

### ISSUE THREAD

**Issue by pravi** [collectiveidea/tinder#76]
Do you follow semantic versioning as defined by semver.org? If yes, can you mention it is README. If not, can you consider it?

**Comment by pravi** [comment]
@bkeepers @bryckbost can you reply?

**Comment by bkeepers** [comment]
@pravi I no longer maintain tinder, and it looks like there hasn't been a release in several years.

**Comment by asheren** [comment]
Hi there! We're doing some open source maintenance work and closing old issues. If this issue is still applicable or you would still like it to be addressed, please re-open the issue by April 17, 2017. Thanks!
