### ISSUE TITLE
Tinder Boost API

### ISSUE THREAD

**Issue by rktrkt** [collectiveidea/tinder#78]
Currently [Tinder Boost](http://blog.gotinder.com/skip-the-line-with-tinder-boost/) is rolled out in Australia to boost the visibility of your profile. In the past Tinder rolled out the UI of features in Australia first, but the features have been active for all countries.

Can somebody in Australia discover the API call of the Boost Feature [with Charles Proxy](http://hungtran.co/discovering-tinders-private-api/) or another proxy so the boost api can be added to the software?

As long as UI is not rolled out in every country activating this will give you much more boost than when it's live because there's no competition for your bots 😁

**Comment by asheren** [comment]
Hi there! We're doing some open source maintenance work and closing old issues. If this issue is still applicable or you would still like it to be addressed, please re-open the issue by April 17, 2017. Thanks!
